name: 'Publish .NET Content Snaps'
description: 'A sequence of steps to publish the Canonical .NET Content Snaps'

inputs:
  artifact-name:
    description: 'The name of the artifact, without architecture'
    required: true
  architecture:
    description: 'The architecture of the artifact'
    required: true
  store-token:
    description: 'The Snap Store login token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      id: download-artifact
      with:
        name: ${{ inputs.artifact-name }}-${{ inputs.architecture }}
    - name: Gather filename
      id: gather-filename
      shell: bash
      env:
        ARTIFACT_NAME: ${{ inputs.artifact-name }}-${{ inputs.architecture }}
        ARTIFACT_PATH: ${{ steps.download-artifact.outputs.download-path }}
      run: |
        ls -la $ARTIFACT_PATH
        SNAP_NAME=$(echo $ARTIFACT_NAME | cut -d- -f-3)
        SNAP_FILE_NAME=$(ls ${ARTIFACT_PATH}/${SNAP_NAME}*.snap)
        echo "SNAP_PATH=${SNAP_FILE_NAME}" >> "$GITHUB_OUTPUT"
    - uses: snapcore/action-publish@v1
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ inputs.store-token }}
      with:
        snap: ${{ steps.gather-filename.outputs.SNAP_PATH }}
        release: edge
