name: dotnet-runtime-80
base: core20
version: 8.0.7
summary: Cross-Platform .NET Core Runtime.
description: |
  .NET Core runtimes and libraries which are optimized for running .NET Core apps in production. See https://dot.net/core.
  .NET Core is a general purpose development platform maintained by Microsoft.

grade: stable
confinement: strict

apps:
  dotnet:
    command: dotnet
    plugs:
      - network
      - network-bind
      - removable-media
      - home

slots:
  dotnet-runtime:
    content: dotnet-runtime-80
    interface: content
    read: [/]

parts:
  dotnet-runtime:
    plugin: dump
    source: https://download.visualstudio.microsoft.com/download/pr/cf3418ca-0e14-4b76-b615-ac2f2497f8ec/2583028ea52460cb1534d929dc7970fe/dotnet-runtime-8.0.7-linux-x64.tar.gz
    source-checksum: sha512/88e9ac34ad5ac76eec5499f2eb8d1aa35076518c842854ec1053953d34969c7bf1c5b2dbce245dbace3a18c3b8a4c79d2ef2d2ff105ce9d17cbbdbe813d8b16f
    stage-packages:
      - libicu66
      - liblttng-ust0

  mounts:
    plugin: dump
    after: 
      - dotnet-runtime
    source: .
    override-build: |
      RUNTIME_VERSION=$(ls ${SNAPCRAFT_STAGE}/shared/Microsoft.NETCore.App/ | grep 8.0)
      
      for file in mounts/*; do
        sed -i "s/{RUNTIME_VERSION}/$RUNTIME_VERSION/g" $file
        sed -i "s/{SNAP}/$SNAPCRAFT_PROJECT_NAME/g" $file
        if [[ "$file" == *"{RUNTIME_VERSION}"* ]]; then
          new_file=$(echo "$file" | sed "s/{RUNTIME_VERSION}/$RUNTIME_VERSION/")
          mv "$file" "$new_file"
          echo "Renamed '$file' to '$new_file'"
        fi
      done

      snapcraftctl build
