name: dotnet-sdk-80
base: core22
adopt-info: dotnet-sdk
summary: .NET 8 SDK
description: |
  The .NET SDK is a set of libraries and tools that developers use to create
  .NET applications and libraries.

grade: stable
confinement: strict

package-repositories:
 - type: apt
   ppa: dotnet/snaps
   priority: always

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

slots:
  dotnet-sdk:
    interface: content
    content: dotnet-sdk-80
    source:
      read:
        - $SNAP/usr/lib/dotnet

parts:
  dotnet-sdk:
    plugin: nil
    source: .
    build-packages:
      - jq
    stage-packages:
      - dotnet-sdk-8.0
    override-stage: |
      craftctl default

      DOTNET_SDK_VERSION=$(LD_LIBRARY_PATH=${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR} \
        ${CRAFT_STAGE}/usr/lib/dotnet/dotnet --version)

      if [ -f ${CRAFT_PART_SRC}/GIT_SHA ]; then
        jq -n --arg repo "https://github.com/canonical/dotnet-content-snaps" \
          --arg commit "$(cat ${CRAFT_PART_SRC}/GIT_SHA)" \
          '{repository: $repo, commit: $commit}' > ${CRAFT_PRIME}/release.json
      fi

      craftctl set version="${DOTNET_SDK_VERSION}"

  mounts:
    plugin: dump
    source: .
    after:
      - dotnet-sdk
    override-build: |
      RUNTIME_VERSION=$(ls ${CRAFT_STAGE}/usr/lib/dotnet/shared/Microsoft.NETCore.App/ | grep 8.0)
      SDK_VERSION=$(ls ${CRAFT_STAGE}/usr/lib/dotnet/sdk | grep 8.0)
      
      if [ "${CRAFT_ARCH_BUILD_FOR}" = "amd64" ]; then
        ARCH="x64"
      elif [ "${CRAFT_ARCH_BUILD_FOR}" = "arm64" ]; then
        ARCH="arm64"
      else
        echo "Unknown architecture (${CRAFT_ARCH_BUILD_FOR})"
        exit 1
      fi

      for file in mounts/*; do
        sed -i "s/{RUNTIME_VERSION}/$RUNTIME_VERSION/g" $file
        sed -i "s/{SDK_VERSION}/$SDK_VERSION/g" $file
        sed -i "s/{SNAP}/$CRAFT_PROJECT_NAME/g" $file
        sed -i "s/{ARCH}/$ARCH/g" $file

        new_file_name="$(echo "$file" \
          | sed "s/{RUNTIME_VERSION}/$RUNTIME_VERSION/" \
          | sed "s/{SDK_VERSION}/$SDK_VERSION/" \
          | sed "s/{ARCH}/$ARCH/")"

        if [[ "$file" != "$new_file_name" ]]; then  
          mv "$file" "$new_file_name"
          echo "Renamed '$file' to '$new_file_name'"
        fi
      done

      craftctl default
    prime:
      - mounts/

lint:
  ignore:
    - library:
      - usr/lib/**/libicu*
      - usr/lib/**/liblttng-ust-*
      - usr/lib/**/libunwind-*
