name: build-dotnet-80

on:
  push:
    branches: main
    paths:
      - snaps/dotnet-runtime-80/**
      - snaps/aspnetcore-runtime-80/**
      - snaps/dotnet-sdk-80/**
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/template-build.yaml
    with:
      version: '8.0'
      build-dotnet-runtime: true
      build-aspnetcore-runtime: true
      build-dotnet-sdk: true
  test:
    uses: ./.github/workflows/template-test.yaml
    needs: build
    with:
      version: '8.0'
      test-dotnet-runtime: true
      test-aspnetcore-runtime: true
      test-dotnet-sdk: true
  publish:
    uses: ./.github/workflows/template-publish.yaml
    needs: test
    if: ${{ contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) && github.ref_name == 'main' }}
    with:
      version: '8.0'
      publish-dotnet-runtime: true
      publish-aspnetcore-runtime: true
      publish-dotnet-sdk: true
    secrets:
      snap-store-token: ${{ secrets.DOTNET8_SNAP_STORE_LOGIN }}
